Machine Learning Tips and Tricks Translation
erfannoury/cheatsheet-translation pull request #5
Opened 2018-09-21 17:34 UTC by erfannoury

2018-09-22 07:54 UTC, mhd-karimi requested changes
There are more half-space improvements that I didn't keep record. like:
All `میشوند` could be changed to ‍‍`می‌شوند`,
All `میکنیم` could be changed to ‍‍`می‌کنیم`,
All `میگیرند` could be changed to ‍‍`می‌گیرند`,
All `میدهد` could be changed to ‍‍`می‌دهد`.

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +1. برگه ی یادداشت  نکات و ترفندهای یادگیری ماشین
Cheatsheet: `راهنمای کوتاه`
As it is used in other files

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +2. معیارهای دسته بندی
Classification: `طبقه بندی`
or all other translation should be changed to `دسته بندی`

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +3. در اینجا معیارهای اساسی و مهم برای پیگیری در زمینه ی طبقه بندی دودویی و به منظور ارزیابی عملکرد مدل ارائه میشوند.
for `here are` sentence type we've used `در زیر آمده‌اند`
`معیارهای اساسی و مهم برای پیگیری در زمینه‌ی طبقه‌بندی دودویی و به منظور ارزیابی عملکرد مدل در زیر آمده‌اند`

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +5. [کلاس پیش¬بینی¬شده، کلاس واقعی]
class: `طبقه` or ‍‍`دسته`
based of classification translation

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +15. AUC – مساحت زير منحني که تحت عنوان AUC یا AUROC نیز شناخته میشود عبارتست از سطح زیر ROC که در شکل زیر نشان داده شده است:
`منحنی`
arabic `ي`

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +20. معیارهای اصلی – از معیارهای زیر معمولا برای ارزیابی عملکرد مدلهای رگرسیون با توجه به تعداد متغیرهای n ی که در نظر میگیرند،استفاده میشود:
‍`20. معیارهای اصلی – از معیارهای زیر معمولا برای ارزیابی عملکرد مدل‌های رگرسیون با توجه به تعداد متغیرهای n که در نظر میگیرند، استفاده می‌شود:`

remove `nی`
space after comma
half-space correction

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +28. هنگامی که مدل انتخاب شد،آن را بر روی کل مجموعه داده ها آموزش داده و بر روی مجموعه داده های دیده نشده آزمایش میشود. این داده ها در شکل زیر نشان داده شده اند:
`هنگامی که مدل انتخاب شد، آن را بر روی کل مجموعه داده‌ها آموزش داده و بر روی مجموعه داده های دیده نشده آزمایش می‌شود. این داده‌ها در شکل زیر نشان داده شده‌اند`

half-space correction

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +30. [آموزش در K-1 برابر و ارزیابی روی موارد باقیمانده، آموزش در N-P مشاهده و ارزیابی روی p مورد باقیمانده]
fold: `بخش`

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +32. متداولترین روش عبارتست از اعتبار سنجی متقاطع k برابر [بخشی] که داده های آموزشی را به k بخش تقسیم میکند تا مدل را روی یک بخش ثابت کند و در عین حال مدل را روی k-1 بخش دیگر آموزش دهد که همه ی آنها k
You are using `برابر` and `بخش` together.
Is `برابر` a common translation for `fold` that I am not aware of?

تا مدل روی یک بخش `ارزیابی` شود

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +33. تنظیم – هدف از روش تنظیم عبارتست از جلوگیری از بیش برارزش شدن مدل توسط داده ها و در نتیجه فائق آمدن با مشکل واریانس بالا.جدول زیر خلاصه ای از انواع روشهای متداول در تنظیم را ارائه میدهد.
هدف از رویه تنظیم جلوگیری از بیش‌برازش مدل بر داده‌ها است که باعث فائق آمدن بر مشکل واریانس بالا می‌شود

procedure: `رویه`
Overfit: `بیش‌برازش` 
فائق آمدن `بر`

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +36. انحراف– انحراف مدل عبارتست از اختلاف بین پیش بینی مورد انتظار و مدل صحیح که تلاش میکنیم برای نقاط داده معینی پیش بینی کنیم.
bias: پیش‌قدر
data point: نمونه داده
They have been used in other files too.

It is used in the following statements.

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +40. [خطای بالای آموزش، خطای آموزش نزدیک به خطای آزمایش، انحراف زیاد، خطای آموزش کمی کمتر از خطای آزمایش، خطای آموزش بسیار کم، خطای آموزش بسیار پایینتر از خطای آزمایش، واریانس بالا]
خطای آموزش بسیار `کم‌تر` از خطای آزمایش
Like other `lower` translation

2018-09-22 07:54 UTC, m-karimi commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +42. تجزیه و تحلیل خطا - تجزیه و تحلیل خطا به آنالیز علت اصلی اختلاف در عملکرد بین مدلهای کنونی و کامل میپردازد.
Maybe using `بررسی` instead of `آنالیز`

2018-09-22 18:49 UTC, erfannoury commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +2. معیارهای دسته بندی
I have used کلاسه‌بندی for classification.

2018-09-22 18:50 UTC, erfannoury commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +5. [کلاس پیش¬بینی¬شده، کلاس واقعی]
I think دسته is a better translation. I will make sure to change all translations of class to دسته and classification to دسته‌بندی throughout the documents.

2018-09-22 18:51 UTC, erfannoury commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +32. متداولترین روش عبارتست از اعتبار سنجی متقاطع k برابر [بخشی] که داده های آموزشی را به k بخش تقسیم میکند تا مدل را روی یک بخش ثابت کند و در عین حال مدل را روی k-1 بخش دیگر آموزش دهد که همه ی آنها k
برابر is a correct translation for something like "k-fold improvement", but it's not a correct translation here.

2018-09-23 12:34 UTC, AlisterTA commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +2. معیارهای دسته بندی
I decided to stick with "دسته‌بندی"

2018-09-23 12:44 UTC, AlisterTA commented on fa/cheatsheet-machine-learning-tips-and-tricks.md
> +20. معیارهای اصلی – از معیارهای زیر معمولا برای ارزیابی عملکرد مدلهای رگرسیون با توجه به تعداد متغیرهای n ی که در نظر میگیرند،استفاده میشود:
please have another look,the character [n] was included in the original context.can i safely change it  to 

[معیارهای اصلی – از معیارهای زیر معمولا برای ارزیابی عملکرد مدلهای رگرسیون با توجه به تعداد n متغیری که در نظر می‌گیرند، استفاده میشود:]

2018-09-23 12:48 UTC, mhd-karimi reviewed
I think you've missed these changes:
29- half-spaces and space after the dot
30- fold: بخش
33- overfit: بیش‌برازش
بیش‌برازش مدل توسط داده‌ها

2018-09-23 12:49 UTC, mhd-karimi approved these changes

2018-10-05 01:40 UTC, closed without merging